# Generated by Django 4.1.5 on 2023-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_product_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
