# Generated by Django 4.1.5 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
