# Generated by Django 4.1.5 on 2023-01-06 23:46

import accounts.others_models.model_profile
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(help_text='Informe seu nome completo', max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Seu melhor e-mail. Será usado para login também.', max_length=254, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este username.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e os símbolos @/./+/-/_ são permitidos.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Usuário')),
                ('is_staff', models.BooleanField(default=False, help_text='Pode logar no Admin', verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Usuário com acesso irrestrito no sistema.', verbose_name='Usuário administrador')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque esta opção em vez de deletar o usuário.', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de cadastro')),
                ('user_clipse', models.BooleanField(default=False, help_text='Usuário com acesso irrestrito no sistema.', verbose_name='Usuário Clipse')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('adm_sistem_access', 'Administrador sistema'), ('user_suppliers_access', 'Fornecedor')], max_length=100, null=True, verbose_name='Tipo de usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', helpers.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.others_models.model_profile.upload_to)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=accounts.others_models.model_profile.upload_to)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social')),
                ('CNPJ', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('fantasy_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Endereço')),
                ('complement_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro')),
                ('house_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('pin_code', models.CharField(blank=True, help_text='Exemplo: 64800-000', max_length=20, null=True, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50, null=True, verbose_name='Estado')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Telefone')),
                ('email_busines', models.CharField(blank=True, max_length=120, null=True, verbose_name='E-mail')),
                ('bank_details', models.CharField(blank=True, max_length=70, null=True, verbose_name='Dados Bancários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do usuário',
                'verbose_name_plural': 'Perfil dos usuários',
            },
        ),
    ]
