# Generated by Django 4.1.5 on 2023-01-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_clipse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Razão Social'),
        ),
    ]
