# Generated by Django 4.1.5 on 2023-01-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('adm_sistem_access', 'Administrador sistema'), ('user_suppliers_access', 'Fornecedor'), ('user_commom_access', 'Usuário')], max_length=100, null=True, verbose_name='Tipo de usuário'),
        ),
    ]
