# Generated by Django 4.1.5 on 2023-01-14 18:25

import accounts.others_models.model_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.others_models.model_profile.upload_to, verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.others_models.model_profile.upload_to, verbose_name='Imagem do perfil'),
        ),
    ]
